[project]
dynamic = ['dependencies']

[tool.setuptools.dynamic]
dependencies  = {file = ['core_requirements.txt']}

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
